"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {ArrowRight,ArrowUpRight,Check,House,ChartNoAxesColumnIncreasing,Search,KeyRound} from "lucide-react";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {ownerCities,propertyTypes} from "@/lib/owner-enquiry";
import {assessmentServices,areaOptions,serviceDetails,initialQuizData,validateQuizStep,quizMailto,quizLocation,type PropertyQuizData,type QuizError} from "@/lib/property-quiz";
const steps=["Service","Property","Details","Contact"];
const icons=[House,KeyRound,Search,ChartNoAxesColumnIncreasing];
export function PropertyQuiz(){
 const [data,setData]=useState<PropertyQuizData>({...initialQuizData,details:{}}),[step,setStep]=useState(0),[visited,setVisited]=useState(0),[error,setError]=useState<QuizError|null>(null),[ready,setReady]=useState(false);
 const form=useRef<HTMLFormElement>(null),heading=useRef<HTMLHeadingElement>(null),mounted=useRef(false),pendingFocus=useRef<string|null>(null);
 useEffect(()=>{if(!mounted.current){mounted.current=true;return;}if(pendingFocus.current){document.getElementById(`quiz-${pendingFocus.current}`)?.focus();pendingFocus.current=null;}else heading.current?.focus();},[step]);
 const update=(field:keyof PropertyQuizData,value:string)=>{setData(d=>({...d,[field]:value}));setError(null);setReady(false);};
 const go=(next:number)=>{setError(null);setReady(false);setStep(next);};
 const invalid=(issue:QuizError,at:number)=>{setError(issue);if(at!==step){pendingFocus.current=issue.field;setStep(at);}else document.getElementById(`quiz-${issue.field}`)?.focus();};
 const submit=(event:FormEvent)=>{event.preventDefault();setReady(false);if(step<3){const issue=validateQuizStep(step,data);if(issue){invalid(issue,step);return;}setVisited(v=>Math.max(v,step+1));go(step+1);return;}for(let i=0;i<4;i++){const issue=validateQuizStep(i,data);if(issue){invalid(issue,i);return;}}setError(null);window.location.href=quizMailto(data);setReady(true);};
 const select=(field:string,label:string,options:readonly string[],value:string,onChange:(value:string)=>void)=><div className="quiz-field" key={field}><label htmlFor={`quiz-${field}`}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger id={`quiz-${field}`} className="quiz-select" aria-required="true" aria-invalid={error?.field===field} aria-describedby={error?.field===field?"quiz-error":undefined}><SelectValue placeholder="Please select"/></SelectTrigger><SelectContent className="owner-select-options" position="popper" data-lenis-prevent>{options.map(option=><SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select></div>;
 const input=(field:keyof PropertyQuizData,label:string,type="text",placeholder="",maxLength=100)=><label className="quiz-field" key={field} htmlFor={`quiz-${field}`}>{label}<input id={`quiz-${field}`} name={field} type={type} value={String(data[field])} onChange={e=>update(field,e.target.value)} placeholder={placeholder} maxLength={maxLength} required autoComplete={field==="name"?"name":field==="email"?"email":field==="phone"?"tel":"off"} aria-invalid={error?.field===field} aria-describedby={error?.field===field?"quiz-error":undefined}/></label>;
 const service=assessmentServices.find(s=>s.id===data.service);
 return <section className="property-quiz section-wrap" id="property-assessment" aria-labelledby="quiz-title">
  <div className="quiz-intro"><p className="eyebrow">A CONVERSATION ABOUT YOUR PROPERTY</p><h2 id="quiz-title">Let’s understand<br/><em>your property.</em></h2><p>Tell us a little about your property and your plans. Share its location, condition and your priorities to start a conversation about the right next steps.</p></div>
  <form ref={form} onSubmit={submit} noValidate className="quiz-panel">
   <nav aria-label="Property enquiry steps"><ol className="quiz-steps">{steps.map((label,i)=><li key={label}><button type="button" disabled={i>visited} aria-current={i===step?"step":undefined} onClick={()=>{if(i<=step){go(i);return;}for(let n=0;n<i;n++){const issue=validateQuizStep(n,data);if(issue){invalid(issue,n);return;}}go(i);}}><span className="quiz-step-number">{i<step?<Check size={15}/>:String(i+1).padStart(2,"0")}</span><span>{label}</span></button></li>)}</ol></nav>
   <div className="quiz-progress" aria-hidden="true"><span style={{width:`${(step+1)*25}%`}}/></div>
   <div className="quiz-step-content" key={step}>
    <div className="quiz-step-heading"><p className="eyebrow">STEP {String(step+1).padStart(2,"0")} / 04</p><h3 ref={heading} tabIndex={-1}>{["How can we help you?",data.service==="investment"?"Where do you have in mind?":"Tell us about your property.","A few details make the difference.","Let’s start the conversation."][step]}</h3><p>{["Choose the service you are interested in.","An approximate size is enough to get started.","Help us understand what matters to you.","Check your answers and tell us how to reach you."][step]}</p></div>
    {step===0&&<RadioGroup className="quiz-services" value={data.service} onValueChange={value=>{setData(d=>({...d,service:value,details:d.service===value?d.details:{}}));setVisited(1);setError(null);}} aria-label="Choose a service" aria-describedby={error?"quiz-error":undefined}>{assessmentServices.map((s,i)=>{const Icon=icons[i];return <label className="quiz-service" key={s.id}><RadioGroupItem id={i===0?"quiz-service":`quiz-service-${s.id}`} value={s.id} aria-label={s.title}/><Icon className="quiz-service-icon" size={27} strokeWidth={1.2}/><span className="quiz-service-title">{s.title}</span><span className="quiz-service-description">{s.description}</span></label>;})}</RadioGroup>}
    {step===1&&<div className="quiz-fields">{select("country","Country",["Georgia","Other"],data.country,v=>update("country",v))}{data.country==="Other"?<>{input("otherCountry","Country name","text","Country",80)}{input("otherCity","City or region","text","City or region")}</>:select("city","Destination or city",ownerCities,data.city,v=>update("city",v))}{select("propertyType","Property type",propertyTypes,data.propertyType,v=>update("propertyType",v))}{select("area",data.service==="investment"?"Preferred property size":"Total area",areaOptions,data.area,v=>update("area",v))}</div>}
    {step===2&&<div className="quiz-fields">{(serviceDetails[data.service]||[]).map(f=>f.options?select(`detail-${f.key}`,f.label,f.options,data.details[f.key]||"",value=>{setData(d=>({...d,details:{...d.details,[f.key]:value}}));setError(null);}):<label className="quiz-field" key={f.key} htmlFor={`quiz-detail-${f.key}`}>{f.label}<input id={`quiz-detail-${f.key}`} value={data.details[f.key]||""} placeholder={f.placeholder} maxLength={100} onChange={e=>{setData(d=>({...d,details:{...d.details,[f.key]:e.target.value}}));setError(null);}} aria-invalid={error?.field===`detail-${f.key}`} aria-describedby={error?.field===`detail-${f.key}`?"quiz-error":undefined}/></label>)}<label className="quiz-field quiz-wide" htmlFor="quiz-notes">Anything else we should know? (optional)<textarea id="quiz-notes" value={data.notes} onChange={e=>update("notes",e.target.value)} maxLength={1500} rows={3} placeholder="A building name, a question or anything important to your plans." aria-invalid={error?.field==="notes"}/></label></div>}
    {step===3&&<div className="quiz-contact-layout"><div className="quiz-fields">{input("name","Name","text","Your full name")}{input("email","Email","email","you@example.com",254)}{input("phone","Phone","tel","+995 ...",30)}{select("contactMethod","Preferred contact",["Email","Phone"],data.contactMethod,v=>update("contactMethod",v))}</div><aside className="quiz-review" aria-label="Your enquiry summary"><p className="eyebrow">YOUR ENQUIRY</p><div className="quiz-review-row"><strong>{service?.title}</strong><button type="button" onClick={()=>go(0)} aria-label="Edit service">Edit</button></div><div className="quiz-review-row"><p>{quizLocation(data)}<br/>{data.propertyType}<br/>{data.area}</p><button type="button" onClick={()=>go(1)} aria-label="Edit property">Edit</button></div><div className="quiz-review-row"><dl>{(serviceDetails[data.service]||[]).filter(f=>data.details[f.key]).map(f=><div key={f.key}><dt>{f.label}</dt><dd>{data.details[f.key]}</dd></div>)}{data.notes&&<div><dt>Additional notes</dt><dd>{data.notes}</dd></div>}</dl><button type="button" onClick={()=>go(2)} aria-label="Edit details">Edit</button></div></aside></div>}
   </div>
   {error&&<p className="quiz-error" id="quiz-error" role="alert">{error.message}</p>}
   <div className="quiz-actions">{step>0?<button type="button" className="quiz-back" onClick={()=>go(step-1)}>Back</button>:<p>Four simple steps.<br/>One thoughtful conversation.</p>}<button type="submit" className="button">{step===3?"Continue by email":"Continue"}{step===3?<ArrowUpRight size={19}/>:<ArrowRight size={19}/>}</button></div>
   {step===3&&<p className="quiz-delivery" role={ready?"status":undefined}>{ready?"Your email app should open with your answers. Send the email there to complete your request.":"All contact fields are required. Continue opens your email app with your answers."} <a href="mailto:info@luxuryaparthotel.ge">info@luxuryaparthotel.ge</a></p>}
  </form>
 </section>;
}
