import { ArrowUpRight } from "lucide-react";
import { InnerShell } from "@/components/inner-shell";
import { ScrollChapter } from "@/components/scroll-chapter";
import { EditorialImage } from "@/components/editorial-image";
export const metadata={title:"About Us | Luxury Apart Hotel",description:"Our story, our destinations and our approach to hospitality. Luxury Apart Hotel, operating in Georgia since 2015."};
const directions=[
 ["Property Management","Daily and monthly apartment rentals."],
 ["Investment & Sales","Investment, purchase, and sale of premium real estate."],
 ["Luxury Laundry Service","Our own full-cycle laundry, serving both apartments under our management and partner hotels in Batumi."],
 ["Luxury Housekeeping Service","Professional, hotel-level cleaning and housekeeping."]
];
export default function AboutPage(){return <InnerShell current="/about-us/">
 <ScrollChapter label="ABOUT US" title="Your Premium Stay" italic="in Georgia." image="about-waterfront" alt="Batumi’s skyline seen across the calm Black Sea" description="Luxury apartments in Batumi and New Gudauri, managed with care, expertise and hospitality." secondTitle="Care. Expertise." secondItalic="Hospitality." href="https://luxuryaparthotel.ge/apartments/" action="Explore our apartments"/>
 <section className="about-story section-wrap editorial-section" id="our-story"><p className="eyebrow" data-reveal>ABOUT US / SINCE 2015</p><div data-reveal><h2>A considered approach<br/><em>to feeling at home.</em></h2><div className="about-story-copy"><p>Luxury Apart Hotel is a professional property management company operating since 2015. We specialize in premium-class apartments in Georgia’s key destinations — Batumi (Orbi City) and New Gudauri (Four Seasons).</p><p>Our team combines deep market expertise with high operational standards, ensuring exceptional guest experiences and consistent returns for property owners.</p></div></div></section>
 <section className="directions-section editorial-section"><div className="section-wrap"><div className="directions-heading" data-reveal><p className="eyebrow">OUR DIRECTIONS</p><h2>Several directions.<br/><em>One standard.</em></h2><p>Luxury Apart Hotel brings together several directions under one standard of quality:</p></div><div className="direction-list">{directions.map(([title,text],i)=><article key={title} data-reveal><span className="direction-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="about-values editorial-section section-wrap"><div data-reveal><p className="eyebrow">WHY CHOOSE US</p><h2>Confidence,<br/><em>in the details.</em></h2></div><div className="values-list"><p data-reveal><span>01</span>Full-cycle management — from bookings to cleaning and reporting</p><p data-reveal><span>02</span>Tailored approach for every guest and investor</p><p data-reveal><span>03</span>Transparency, trust, and a long-standing reputation</p></div></section>
 <section className="locations-section section-wrap editorial-section"><div className="section-heading" data-reveal><div><p className="eyebrow">OUR LOCATIONS</p><h2>From the sea<br/><em>to the mountains.</em></h2></div><p className="heading-aside">Two destinations in Georgia.<br/>A single standard of hospitality.</p></div><div className="location-pair"><article data-reveal><figure><EditorialImage name="batumi-coast" alt="The Black Sea and Batumi coastline" sizes="(max-width:700px) 100vw, 50vw"/></figure><p className="eyebrow">BATUMI / ORBI CITY</p><h3>A life by the water.</h3><p>Batumi — Orbi City: modern seafront apartments just 50 meters from the sea. Nearby you’ll find the boulevard, gardens, restaurants, a children’s amusement area, and a dancing fountain lake, along with 24/7 convenience stores. The complex offers 24/7 security, and concierge service for guests.</p><a className="text-link" href="/guides-insights/batumi-stay-guide/">Discover Batumi<ArrowUpRight size={17}/></a></article><article data-reveal><figure><EditorialImage name="gudauri-mountains" alt="Snowy peaks in Gudauri" sizes="(max-width:700px) 100vw, 50vw"/></figure><p className="eyebrow">NEW GUDAURI / FOUR SEASONS</p><h3>A different perspective.</h3><p>New Gudauri — Four Seasons: mountain-view apartments just 100 meters from the cable car and ski lifts. Nearby there’s an ice-skating rink for both adults and children, ski &amp; snowboard rental shops (skis, snowboards, helmets, goggles, and all necessary gear), plus 24/7 shops and restaurants. Both surface and underground parking are available, along with 24/7 security and concierge service — ideal for winter vacations and investment.</p><a className="text-link" href="/guides-insights/gudauri-winter-guide/">Discover Gudauri<ArrowUpRight size={17}/></a></article></div></section>
 <section className="international-section editorial-section"><div className="section-wrap"><p className="eyebrow" data-reveal>INTERNATIONAL PRESENCE</p><div className="international-copy" data-reveal><h2>Our horizon<br/><em>is growing.</em></h2><p>Since 2025, Luxury Apart Hotel has been expanding beyond Georgia. We have launched a new direction of exclusive tours and travel experiences in Zanzibar (Tanzania), and are developing partnerships in Spain and Dubai, growing an international network of premium hospitality.</p></div><div className="destination-names" aria-label="International destinations"><span>Georgia</span><span>Zanzibar</span><span>Spain</span><span>Dubai</span></div></div></section>
 <section className="guest-offers editorial-section section-wrap" data-reveal><p className="eyebrow">GUEST OFFERS</p><h2>More to look<br/><em>forward to.</em></h2><p>We regularly prepare special offers and seasonal packages for our guests — including ready-made packages for Zanzibar getaways — so that every journey with Luxury Apart Hotel is both comfortable and rewarding.</p><a className="text-link" href="mailto:info@luxuryaparthotel.ge?subject=Guest%20offers">Ask about current offers<ArrowUpRight size={18}/></a></section>
 <section className="next-chapter section-wrap" data-reveal><p className="eyebrow">THE NEXT CHAPTER</p><div><p>Since 2025, Luxury Apart Hotel has been expanding internationally, stepping beyond Georgia’s borders.</p><p>We are launching a new hospitality and tourism direction — exclusive travel experiences and tours in Zanzibar (Tanzania).</p><p>This new chapter combines our long-standing expertise in property management with the growing potential of international tourism.</p><p>Our mission is to build a global hospitality network under one standard of excellence — from the snowy peaks of Gudauri to the tropical shores of the Indian Ocean.</p></div></section>
 <ScrollChapter closing label="LUXURY APART HOTEL" title="Hospitality into reliability." italic="Comfort into a lifestyle." secondTitle="Your next chapter" secondItalic="starts here." image="batumi-final" alt="Palms on the Batumi waterfront" href="https://luxuryaparthotel.ge/apartments/" action="Explore our apartments"/>
 </InnerShell>;}
