import Home from './app/page';import About from './app/about-us/page';import Owners from './app/for-owners/page';import Contact from './app/contact-us/page';import Experiences from './app/experiences/page';import Guides from './app/guides-insights/page';
import {InnerShell} from './components/inner-shell';import {SiteHeader,SiteFooter} from './components/site-chrome';import {EditorialImage} from './components/editorial-image';import {wpData} from './wp-data';import {ArrowLeft,ArrowUpRight} from 'lucide-react';
export {SiteFooter};export const StaticHeader=()=> <SiteHeader menuOpen={false} onMenuChange={()=>{}}/>;
export function WPApp({view=wpData?.view||'home'}:{view?:string}){
 if(view==='home')return <Home/>;if(view==='about')return <About/>;if(view==='owners')return <Owners/>;if(view==='contact')return <Contact/>;if(view==='experiences')return <Experiences/>;if(view==='guides')return <Guides/>;
 const article=wpData?.article;if(article){const base=article.kind==='lux_guide'?'guides-insights':'experiences';
  if(article.layout==='service')return <InnerShell current="/experiences/"><header className="service-template-heading section-wrap"><a className="article-back" href="/experiences/"><ArrowLeft size={16}/>All experiences</a><p className="eyebrow">{article.category}</p><h1>{article.title}</h1><p>{article.summary}</p></header>{article.image&&<div className="section-wrap"><figure className="service-article-cover"><EditorialImage name={article.image} alt={article.alt}/></figure></div>}<div className="service-template-body section-wrap"><div className="service-template-sections"><div className="wp-article-content" dangerouslySetInnerHTML={{__html:article.lead}}/>{article.sections.map((section,i)=><section key={section.id} id={section.id}><span className="eyebrow">{String(i+1).padStart(2,'0')}</span><div><h2>{section.title}</h2><div className="wp-article-content" dangerouslySetInnerHTML={{__html:section.html}}/></div></section>)}</div><aside className="service-template-enquiry"><p className="eyebrow">LET’S TALK</p><h2>Have something<br/><em>in mind?</em></h2><p>Contact our team for enquiries about {article.title.toLowerCase()}.</p><a className="button" href={`mailto:info@luxuryaparthotel.ge?subject=${encodeURIComponent(article.title+' enquiry')}`}>Enquire by email<ArrowUpRight size={18}/></a><a className="text-link" href="/contact-us/">All contact details<ArrowUpRight size={16}/></a></aside></div></InnerShell>;
  return <InnerShell current={`/${base}/`}><article className="reading-page"><header className="article-heading section-wrap"><a href={`/${base}/`} className="article-back"><ArrowLeft size={16}/>All {base==='experiences'?'experiences':'guides'}</a><p className="eyebrow">{article.category}</p><h1>{article.title}</h1>{article.summary&&<p className="article-deck">{article.summary}</p>}<div className="article-byline"><span>Luxury Apart Hotel</span><span>LOCAL KNOWLEDGE</span></div></header>{article.image&&<figure className="article-cover"><EditorialImage name={article.image} alt={article.alt} priority/><figcaption>{article.alt}</figcaption></figure>}<div className="reading-layout section-wrap"><aside className="reading-nav"><p className="eyebrow">IN THIS GUIDE</p><nav aria-label="Article contents">{article.sections.map((s,i)=><a key={s.id} href={`#${s.id}`}><span>{String(i+1).padStart(2,'0')}</span>{s.title}</a>)}</nav></aside><div className="reading-body wp-article-content"><div dangerouslySetInnerHTML={{__html:article.lead}}/>{article.sections.map((s,i)=><section id={s.id} key={s.id} data-reveal><span className="eyebrow reading-number">{String(i+1).padStart(2,'0')}</span><h2>{s.title}</h2><div dangerouslySetInnerHTML={{__html:s.html}}/></section>)}<div className="article-stay"><p className="eyebrow">MAKE YOURSELF AT HOME</p><h2>A place to come back to.</h2><p>Explore our apartments in Batumi and New Gudauri.</p><a className="button" href="https://luxuryaparthotel.ge/apartments/">Book an apartment<ArrowUpRight size={18}/></a></div></div></div><div className="journal-signoff section-wrap"><a className="button" href={`/${base}/`}>Keep exploring<ArrowUpRight size={18}/></a></div></article></InnerShell>;
 }

 return <InnerShell current=""><header className="article-heading section-wrap"><h1>{wpData?.page?.title||'Page not found'}</h1></header><div className="section-wrap wp-reading-wrap"><div className="reading-body wp-article-content" dangerouslySetInnerHTML={{__html:wpData?.page?.html||'<p>This page could not be found.</p>'}}/></div></InnerShell>;
}
