<?php
if(!defined('ABSPATH'))exit;
add_action('after_setup_theme',function(){add_theme_support('title-tag');add_theme_support('post-thumbnails');add_theme_support('responsive-embeds');add_theme_support('align-wide');add_theme_support('editor-styles');add_editor_style('editor.css');register_nav_menus(['primary'=>'Primary navigation']);});
function lux_theme_asset($path=''){return get_template_directory_uri().'/assets/'.ltrim($path,'/');}
function lux_view(){if(is_singular(['lux_guide','lux_experience']))return 'article';if(is_404())return '404';$id=get_queried_object_id();$v=get_post_meta($id,'_lux_view',true);if(in_array($v,['home','about','owners','contact','experiences','guides'],true))return $v;if(is_front_page())return 'home';$post=get_queried_object();$slug=$post instanceof WP_Post?$post->post_name:'';return ['about-us'=>'about','for-owners'=>'owners','contact-us'=>'contact','experiences'=>'experiences','guides-insights'=>'guides'][$slug]??'page';}
function lux_links(){
 $links=['/'=>home_url('/')];foreach(['about-us','for-owners','contact-us','experiences','guides-insights'] as $slug){$page=get_page_by_path($slug);$links['/'.$slug.'/']=$page?get_permalink($page):home_url('/'.$slug.'/');}
 foreach(['lux_guide'=>'guides-insights','lux_experience'=>'experiences'] as $type=>$base){$posts=get_posts(['post_type'=>$type,'post_status'=>'publish','numberposts'=>-1]);foreach($posts as $p)$links['/'.$base.'/'.$p->post_name.'/']=get_permalink($p);}
 return $links;
}
function lux_posts($type){return get_posts(['post_type'=>$type,'post_status'=>'publish','posts_per_page'=>-1,'orderby'=>['menu_order'=>'ASC','date'=>'DESC','ID'=>'ASC']]);}
function lux_card_data($p){$tax=$p->post_type==='lux_guide'?'lux_guide_group':'lux_exp_group';$terms=wp_get_object_terms($p->ID,$tax);$term=!is_wp_error($terms)&&$terms?$terms[0]:null;$category=$term?$term->name:'';if($p->post_type==='lux_guide')$category=$term&&$term->slug==='behind-the-stay'?'Our hospitality':($term?$term->name:'Local knowledge');$image=get_the_post_thumbnail_url($p,'large');return ['slug'=>$p->post_name,'title'=>get_the_title($p),'eyebrow'=>$category,'category'=>$category,'description'=>wp_strip_all_tags(get_the_excerpt($p)),'summary'=>wp_strip_all_tags(get_the_excerpt($p)),'image'=>$image?:lux_theme_asset('images/batumi-life.webp'),'alt'=>get_post_meta(get_post_thumbnail_id($p),'_wp_attachment_image_alt',true)?:get_the_title($p),'sections'=>[]];}
function lux_article_sections($html){
 $parts=preg_split('/<h2\b[^>]*>(.*?)<\/h2>/is',$html,-1,PREG_SPLIT_DELIM_CAPTURE);$lead=array_shift($parts);$sections=[];
 for($i=0;$i<count($parts);$i+=2){$title=wp_strip_all_tags($parts[$i]);$sections[]=['id'=>'article-section-'.(count($sections)+1),'title'=>html_entity_decode($title,ENT_QUOTES,get_bloginfo('charset')),'html'=>$parts[$i+1]??''];}
 return ['lead'=>$lead,'sections'=>$sections];
}
function lux_wp_data(){
 $guide_posts=lux_posts('lux_guide');usort($guide_posts,function($a,$b){return (int)get_post_meta($b->ID,'_lux_featured',true)<=>(int)get_post_meta($a->ID,'_lux_featured',true)?:$a->menu_order<=>$b->menu_order;});$exp_posts=lux_posts('lux_experience');$guides=array_map('lux_card_data',$guide_posts);$experiences=array_map('lux_card_data',$exp_posts);$collections=[];
 $terms=taxonomy_exists('lux_exp_group')?get_terms(['taxonomy'=>'lux_exp_group','hide_empty'=>false]):[];$order=['holidays-abroad','georgia-tours','custom-trip','concierge-service'];$descriptions=['holidays-abroad'=>'Somewhere new. A different kind of escape.','georgia-tours'=>'From the Black Sea to the heart of the Caucasus.','custom-trip'=>'Journeys shaped around your own ideas.','concierge-service'=>'Thoughtful help with the details along the way.'];
 if(!is_wp_error($terms)){usort($terms,function($a,$b)use($order){$x=array_search($a->slug,$order,true);$y=array_search($b->slug,$order,true);return ($x===false?99:$x)<=>($y===false?99:$y);});foreach($terms as $term){$slugs=[];foreach($exp_posts as $p)if(has_term($term->term_id,'lux_exp_group',$p))$slugs[]=$p->post_name;$collections[]=['id'=>$term->slug,'title'=>$term->name,'description'=>$term->description?:($descriptions[$term->slug]??''),'slugs'=>$slugs];}}
 $data=['view'=>lux_view(),'assetBase'=>rtrim(lux_theme_asset(),'/'),'homeUrl'=>home_url('/'),'links'=>lux_links(),'guides'=>$guides,'outings'=>[],'experiences'=>$experiences,'collections'=>$collections];
 if($data['view']==='article'){$p=get_queried_object();$card=lux_card_data($p);$data['article']=['title'=>$card['title'],'category'=>$card['category'],'summary'=>$card['summary'],'image'=>$card['image'],'alt'=>$card['alt'],'html'=>apply_filters('the_content',$p->post_content),'kind'=>$p->post_type,'layout'=>$p->post_type==='lux_experience'&&get_post_meta($p->ID,'_lux_layout',true)!=='editorial'?'service':'editorial'];$data['article']=array_merge($data['article'],lux_article_sections($data['article']['html']));}
 elseif($data['view']==='page'&&is_singular()){$p=get_queried_object();$data['page']=['title'=>get_the_title($p),'html'=>apply_filters('the_content',$p->post_content)];}
 return $data;
}
add_action('wp_enqueue_scripts',function(){wp_enqueue_style('luxury-frontend',lux_theme_asset('app/luxury.css'),[],filemtime(get_template_directory().'/assets/app/luxury.css'));wp_enqueue_script('luxury-frontend',lux_theme_asset('app/luxury.js'),[],filemtime(get_template_directory().'/assets/app/luxury.js'),['in_footer'=>true,'strategy'=>'defer']);$data=lux_wp_data();wp_add_inline_script('luxury-frontend','window.LUXURY_WP='.wp_json_encode($data,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT).';','before');});
function lux_snapshot($name){$file=get_template_directory().'/snapshots/'.sanitize_file_name($name).'.html';if(!is_readable($file))return '';$html=file_get_contents($file);$html=str_replace(['/images/','/fonts/'],[lux_theme_asset('images/'),lux_theme_asset('fonts/')],$html);foreach(lux_links() as $from=>$to)$html=str_replace('href="'.$from.'"','href="'.esc_url($to).'"',$html);return preg_replace('/<link\b[^>]*rel="preload"[^>]*>/i','',$html);}
function lux_php_cards($cards,$base){echo '<div class="collection-track">';foreach($cards as $card){$href=lux_links()['/'.$base.'/'.$card['slug'].'/']??home_url('/'.$base.'/'.$card['slug'].'/');?><div class="collection-slide"><a class="experience-article-card" href="<?php echo esc_url($href);?>"><figure><img src="<?php echo esc_url($card['image']);?>" alt="<?php echo esc_attr($card['alt']);?>" width="1200" height="900" loading="lazy"></figure><div class="experience-card-copy"><p class="eyebrow"><?php echo esc_html($card['category']);?></p><h3><?php echo esc_html($card['title']);?></h3><p class="experience-card-description"><?php echo esc_html($card['summary']);?></p><span class="experience-card-link">Read more ↗</span></div></a></div><?php }echo '</div>';}
function lux_server_content(){
 $d=lux_wp_data();$view=$d['view'];if(in_array($view,['home','about','owners','contact'],true)){echo lux_snapshot($view);return;}
 echo lux_snapshot('header');echo '<main class="inner-page" id="top"><div id="content"></div>';
 if($view==='article'){$a=$d['article'];?><article class="reading-page"><header class="article-heading section-wrap"><p class="eyebrow"><?php echo esc_html($a['category']);?></p><h1><?php echo esc_html($a['title']);?></h1><p class="article-deck"><?php echo esc_html($a['summary']);?></p></header><figure class="article-cover"><img src="<?php echo esc_url($a['image']);?>" alt="<?php echo esc_attr($a['alt']);?>" width="1200" height="900"></figure><div class="section-wrap wp-reading-wrap"><div class="reading-body wp-article-content"><?php echo $a['html']; // WordPress the_content output, including allowed blocks. ?></div></div></article><?php }
 elseif(in_array($view,['guides','experiences'],true)){echo '<header class="journal-heading section-wrap"><h1>'.($view==='guides'?'Guides &amp; Insights':'Experiences').'</h1></header><div class="experience-collections section-wrap">';if($view==='guides'){$groups=[['title'=>'A little local knowledge.','cards'=>array_values(array_filter($d['guides'],fn($a)=>$a['category']!=='Our hospitality'))],['title'=>'Care, explained.','cards'=>array_values(array_filter($d['guides'],fn($a)=>$a['category']==='Our hospitality'))]];}else{$groups=[];foreach($d['collections'] as $c)$groups[]=['title'=>$c['title'],'cards'=>array_values(array_filter($d['experiences'],fn($a)=>in_array($a['slug'],$c['slugs'],true)))];}foreach($groups as $g){echo '<section class="experience-collection"><div class="collection-heading"><h2>'.esc_html($g['title']).'</h2></div>';lux_php_cards($g['cards'],$view==='guides'?'guides-insights':'experiences');echo '</section>';}echo '</div>';}
 else {echo '<header class="article-heading section-wrap"><h1>'.esc_html($d['page']['title']??'Page not found').'</h1></header><div class="section-wrap wp-reading-wrap"><div class="reading-body wp-article-content">'.($d['page']['html']??'<p>This page could not be found.</p>').'</div></div>';}
 echo '</main>'.lux_snapshot('footer');
}
