import {wpData} from "@/wp-data";
export type ArticleSection={id:string;title:string;paragraphs:string[];list?:string[]};
export type EditorialArticle={slug:string;title:string;category:string;image:string;alt:string;summary:string;intro:string;sections:ArticleSection[];source:string;sourceLabel:string;map?:string;note?:string};
const seedGuides:EditorialArticle[]=[
 {slug:"batumi-stay-guide",title:"The Batumi stay guide",category:"Batumi",image:"batumi-final",alt:"Batumi boulevard framed by palms",summary:"Sea air, old-town afternoons and the everyday details of a good stay.",intro:"Give Batumi a little room in your plans. Start with the waterfront, make time for the old town, and let the rest of the day unfold around them.",source:"https://georgia.travel/things-to-do-in-batumi",sourceLabel:"Georgia Travel · Things to do in Batumi",sections:[
  {id:"waterfront",title:"Begin by the water",paragraphs:["The boulevard is a natural starting point: a place to walk, pause and get your bearings. The beach, gardens and city skyline give you several different ways to spend an unhurried morning.","Our Orbi City apartments are beside the seafront. A short stroll can become a daily ritual, with a stop for coffee before heading back to your own kitchen."]},
  {id:"old-town",title:"Leave an afternoon for the old town",paragraphs:["Make Piazza Square your starting point for a change of scene. Its arcades, clock tower and mosaic courtyard offer a different view of Batumi from the modern waterfront.","Keep the route flexible. Choose a café when you feel like sitting down, look up at the buildings, and leave yourself time to wander back towards the sea."]},
  {id:"further",title:"A little further afield",paragraphs:["For a greener day, consider Batumi Botanical Garden. Set along the coast at Green Cape, it brings together shaded paths, gardens and views of the Black Sea.","Plan your transport and check current visitor information before leaving. It is an outing to enjoy at your own pace, rather than squeeze between several stops."]},
  {id:"practical",title:"The useful details",paragraphs:["Settle arrival arrangements before your trip. Our team can help arrange an airport or private transfer; availability and prices are confirmed when you enquire."],list:["Keep your apartment address and arrival instructions to hand.","Choose comfortable shoes for a day that combines city streets and the promenade.","Check opening times directly with any attraction you plan to visit.","Ask our team if you need help organising the details of your stay."]}
 ]},
 {slug:"gudauri-winter-guide",title:"New Gudauri winter guide",category:"Gudauri",image:"gudauri-mountains",alt:"Snow-covered mountain panorama in Gudauri",summary:"A considered start to your mountain escape: lifts, rentals and arrival planning.",intro:"A good mountain day starts with a little preparation. Make the practical decisions before you arrive, then leave room to enjoy the view.",source:"https://gudauri.com/about-gudauri/ski-lifts.html",sourceLabel:"Gudauri · Current lift information",note:"Lift operations, snow conditions and transport arrangements change with the weather and season. Confirm them before travelling.",sections:[
  {id:"base",title:"Choose your mountain base",paragraphs:["Luxury Apart Hotel’s Four Seasons apartments are in New Gudauri, close to the cable car and ski lifts. A private kitchen and living space make it easy to find your own rhythm between outings.","Choose your apartment around the people travelling with you. Check the layout, sleeping arrangements and facilities on the individual property page before booking."]},
  {id:"arrival",title:"Plan the journey first",paragraphs:["Confirm your arrival time and transfer arrangements in advance. Mountain travel can be affected by changing weather, so keep your plans flexible and check the latest travel information before departure."]},
  {id:"ski-day",title:"Before your first day on the snow",paragraphs:["Consult the resort’s current lift information and choose equipment suited to your plans. Rental shops near the apartments offer ski and snowboard equipment.","If you need instruction, organise a qualified instructor directly before heading onto the slopes. Take time to get comfortable with the equipment and resort layout."],list:["Check current lift operations and weather.","Arrange equipment and instruction in advance when needed.","Confirm the details of your rental with the provider."]},
  {id:"after",title:"Make space for the quiet hours",paragraphs:["Leave part of the afternoon unscheduled. A meal in your apartment, a slow evening and the mountains outside can be just as much a part of the trip as time on the snow."]}
 ]},
 {slug:"owner-rental-income-guide",title:"The owner’s rental guide",category:"For owners",image:"batumi-architecture",alt:"Contemporary buildings beside Batumi’s waterfront",summary:"What to look for in a property management service, from hosting to reporting.",intro:"Professional management brings a number of everyday responsibilities together. Understanding what is included makes it easier to have a clear, useful conversation about your property.",source:"https://luxuryaparthotel.ge/for-owners/",sourceLabel:"Luxury Apart Hotel · Owner services",sections:[
  {id:"scope",title:"Start with the scope of service",paragraphs:["Ask who handles marketing, reservations, guest communication, cleaning and property checks. These tasks are connected: a reservation only becomes a good stay when the apartment and the team are ready for arrival.","Luxury Apart Hotel brings these operations together with monthly reporting. The right starting point is a conversation about your particular apartment."]},
  {id:"operations",title:"Understand the day-to-day work",paragraphs:["Clarify how guest enquiries are handled and how housekeeping and property control are organised. It is useful to know who you contact and how operational questions reach you."],list:["Apartment onboarding and preparation.","Marketing and reservations.","Guest service and housekeeping.","Property checks and quality control."]},
  {id:"reporting",title:"Keep reporting clear",paragraphs:["Agree what your monthly report will cover and how you will receive it. Ask the team to explain the reporting process and how questions about your apartment are handled.","A management proposal should relate to your property and agreed scope. Discuss any fees, responsibilities and assumptions directly before making a decision."]},
  {id:"next",title:"Begin with your property",paragraphs:["Share the location, apartment type and a little about its current condition with our team. We can then discuss the management services that are relevant to you."]}
 ]},
 {slug:"comfort-service",title:"Comfort & service at a premium standard",category:"Our hospitality",image:"orbi-detail",alt:"A prepared bedroom with a private sea-view balcony",summary:"The apartment essentials and the care behind a considered stay.",intro:"Your apartment gives you privacy and freedom. Our hospitality team takes care of the preparation and practical details around it.",source:"https://luxuryaparthotel.ge/comfort-service-at-a-premium-standard/",sourceLabel:"Luxury Apart Hotel · Comfort & service",sections:[
  {id:"space",title:"Space for your kind of stay",paragraphs:["The collection includes studios, one-bedroom apartments and panoramic two-bedroom apartments. Check each property for its layout and guest capacity.","Private balconies and equipped kitchens give you space for morning coffee, a simple meal and time to yourself."]},
  {id:"included",title:"The everyday essentials",paragraphs:["Apartments are prepared with fresh linen and towels, Wi-Fi, air conditioning and essential guest amenities. The small practical details help you settle in and keep your own routine."]},
  {id:"care",title:"Ready before you arrive",paragraphs:["Preparation includes cleaning, fresh bedding, bathroom care and a final readiness check. Our team remains available before arrival, during your stay and at departure.","Airport and intercity transfers can be arranged on request. Availability and pricing are confirmed when you book."]}
 ]},
 {slug:"prime-locations",title:"Prime locations in Batumi and Gudauri",category:"Our hospitality",image:"batumi-coast",alt:"Batumi’s Black Sea shoreline and skyline",summary:"Two landscapes. Two ways to escape. One standard of care.",intro:"The place around your apartment shapes the stay inside it. Our two Georgian destinations offer very different rhythms.",source:"https://luxuryaparthotel.ge/prime-locations-in-batumi-and-gudauri/",sourceLabel:"Luxury Apart Hotel · Our locations",sections:[
  {id:"batumi",title:"Batumi: a life by the sea",paragraphs:["Orbi City places you on Batumi’s waterfront, close to the boulevard, cafés and everyday essentials. Spend time between the beach, the old town and the city’s contemporary skyline."]},
  {id:"gudauri",title:"Gudauri: a change of altitude",paragraphs:["Four Seasons is in New Gudauri, near the gondola and ski facilities. The mountain setting offers a different kind of space, with alpine scenery beyond the apartment."]},
  {id:"choose",title:"Choose the rhythm that suits you",paragraphs:["Think about how you want to spend the day: walking along the coast, exploring the city or planning time in the mountains. Then select an apartment around your group, travel dates and preferred layout."]}
 ]},
 {slug:"eco-friendly-amenities",title:"Eco-friendly amenities: care in every detail",category:"Our hospitality",image:"orbi-c",alt:"A calm apartment bedroom overlooking the Black Sea",summary:"A closer look at the welcome essentials prepared for our guests.",intro:"The welcome details are part of how an apartment feels when you first arrive. Luxury Apart Hotel’s guest amenities are chosen with both comfort and environmental care in mind.",source:"https://luxuryaparthotel.ge/eco-friendly-amenities-care-in-every-detail/",sourceLabel:"Luxury Apart Hotel · Eco-friendly amenities",sections:[
  {id:"welcome",title:"A considered welcome",paragraphs:["The hotel’s signature welcome set includes shower gel, shampoo and conditioner, hand soap, a vanity kit, a dental kit and slippers."]},
  {id:"materials",title:"Attention to materials",paragraphs:["The company describes its amenity collection as using recyclable and biodegradable materials and natural ingredients. It is one of the details that connects the guest experience with care for the surroundings."]},
  {id:"guests",title:"Prepared for your stay",paragraphs:["These welcome sets are supplied to Luxury Apart Hotel guests in Batumi and Gudauri. If you have questions about a specific product or amenity, ask the team before your arrival."]}
 ]}
];

const seedExperiences:EditorialArticle[]=[
 {slug:"a-day-by-the-sea",title:"A day by the sea",category:"THE WATERFRONT",image:"batumi-life",alt:"Palms and walking paths on Batumi Boulevard",summary:"The boulevard, an open horizon and the pleasure of taking your time.",intro:"You do not need a full itinerary to enjoy Batumi. Start at the boulevard and follow the sea for as long as you feel like walking.",source:"https://georgia.travel/guide-to-batumi-beach",sourceLabel:"Georgia Travel · Batumi’s waterfront",map:"Batumi Boulevard, Georgia",sections:[
  {id:"start",title:"Start slowly",paragraphs:["Leave the apartment with comfortable shoes and no rush. Choose a stretch of the promenade, take in the gardens and stop whenever a view catches your attention."]},
  {id:"discover",title:"Follow the coastline",paragraphs:["The waterfront combines green spaces and newer architecture. Towards Miracle Park, look for the Alphabet Tower and the Ali & Nino sculpture.","You can make this a longer walk or enjoy one small part of the boulevard. There is no need to fit the whole seafront into one outing."]},
  {id:"return",title:"Come back for the evening",paragraphs:["Return when the light begins to soften. Find a place to pause by the water, then head back for a quiet evening in your apartment."]}
 ]},
 {slug:"old-town-and-piazza",title:"An afternoon in the old town",category:"CITY & CULTURE",image:"batumi-old-town",alt:"Batumi Piazza’s arcades and mosaic courtyard",summary:"Arcades, a mosaic courtyard and a different side of Batumi.",intro:"Step away from the high-rise waterfront and spend an afternoon with the streets and squares of central Batumi.",source:"https://georgia.travel/family-attractions/batumi-piazza",sourceLabel:"Georgia Travel · Batumi Piazza",map:"Batumi Piazza, Georgia",sections:[
  {id:"piazza",title:"Begin at Piazza Square",paragraphs:["Piazza sits in the heart of the city’s historic district. Its clock tower and surrounding arcades frame a courtyard with a striking mosaic at its centre.","Look down at the patterns, then up at the architectural details. The square rewards a slower visit."]},
  {id:"wander",title:"Let the streets set the pace",paragraphs:["Continue into the surrounding streets without trying to cover everything. Stop for coffee, look into a shop that catches your eye and enjoy the contrast with the broad waterfront."]},
  {id:"plan",title:"Make it your afternoon",paragraphs:["Piazza is a starting point, not a fixed itinerary. Combine it with another city stop if you wish, or simply find a table and stay a little longer."]}
 ]},
 {slug:"botanical-garden",title:"Where the garden meets the sea",category:"NATURE & SLOW DAYS",image:"batumi-garden",alt:"The Black Sea coastline seen from Batumi Botanical Garden",summary:"Green Cape, leafy paths and a little distance from the city.",intro:"For a change of pace, make time for Batumi Botanical Garden. The landscape brings the greenery of the coast together with views across the Black Sea.",source:"https://georgia.travel/batumi-botanical-garden",sourceLabel:"Georgia Travel · Batumi Botanical Garden",map:"Batumi Botanical Garden, Georgia",sections:[
  {id:"garden",title:"A greener kind of outing",paragraphs:["The garden is at Green Cape, outside central Batumi. Its collections bring together plants from different regions of the world in a coastal setting."]},
  {id:"paths",title:"Take the path that appeals to you",paragraphs:["Allow time for the gardens and viewpoints instead of treating the visit as a quick stop. Pause in the shade and enjoy the contrast between the greenery and the open water."]},
  {id:"visit",title:"Before you set off",paragraphs:["Check current visitor information and transport options before leaving. Wear comfortable walking shoes and plan the outing around your preferred pace.","If you need help arranging transport from your apartment, speak with our team about the available options."]}
 ]}
];

export const guides:EditorialArticle[]=wpData?wpData.guides:seedGuides;
export const experiences:EditorialArticle[]=wpData?wpData.outings:seedExperiences;
